More quotes

diff --git a/gpgchat b/gpgchat
--- a/gpgchat
+++ b/gpgchat
@@ -57,7 +57,7 @@ do
         file_input="${output#???}"
         file_input=${file_input#"${file_input%%[![:space:]]*}"}
         file_input="/tmp/gpgchat/${file_input##*/}"
-        echo -e "\033[33m<<< receiving file \"$file_input\" from $user_remote\033[0m"
+        echo -e "\033[33m<<< receiving file \"$file_input\" from \"$user_remote\"\033[0m"
         ncat -l $port_local | gpg -d --batch --passphrase "$passphrase" 2>/dev/null | base64 -d >"$file_input"
         echo -e "\033[33m<<< file \"$file_input\" ready\033[0m"
     else
@@ -65,7 +65,7 @@ do
     fi
 done &
 
-echo -e "Initiating chat with ${user_remote} at $host, port $port_remote\n"
+echo -e "Initiating chat with \"$user_remote\" at $host, port $port_remote\n"
 while true
 do
     read message
@@ -77,7 +77,7 @@ do
                 file_output=$(python $script_path/getfile.py)
             fi
             if [ -f "$file_output" ]; then
-                echo -e "\033[34m>>> sending file \"$file_output\" to $user_remote\033[0m"
+                echo -e "\033[34m>>> sending file \"$file_output\" to \"$user_remote\"\033[0m"
                 echo "<<<$file_output" | gpg -e -r "$user_remote" | ncat $host $port_remote
                 sleep 1
                 cat "$file_output" | base64 | gpg -e -r "$user_remote" | ncat $host $port_remote
@@ -88,7 +88,7 @@ do
                     echo -e "\033[31m>>> file has not been sent\033[0m"
                 fi
             else
-                [[ -z "$file_output" ]] || echo ">>> \"$file_output\" not found"
+                [[ -z "$file_output" ]] || echo ">>> file \"$file_output\" not found"
             fi
         else
             echo "$message" | gpg -e -r "$user_remote" | ncat $host $port_remote
