Explain about missing dependencies

diff --git a/gpgchat b/gpgchat
--- a/gpgchat
+++ b/gpgchat
@@ -4,6 +4,18 @@ echo
 echo "GPG chat 1.0"
 echo
 
+if ! which gpg>/dev/null; then
+    echo "\"gpg\" missing. Please install the \"gnupg\" package."
+    echo
+    exit 1
+fi
+
+if ! which ncat>/dev/null; then
+    echo "\"ncat\" missing. Please install the \"nmap\" package."
+    echo
+    exit 1
+fi
+
 if [ $# -lt 3 ]; then
     echo "Usage: $0 <remote PGP id> <host> <local port> [remote port]"
     echo
